import { ChatCompletionRequestMessage } from "openai";

export type ChatCompletionModel = "gpt-3.5-turbo" | "gpt-3.5-turbo-0301";

export type ConversationMessage = Omit<ChatCompletionRequestMessage, "name"> & {
    /**
     * A unique identifier for the message (generated by the package, not OpenAI)
     */
    id: string;

    /**
     * The size of the message content in tokens.
     *
     * **Do not use this property as it is only set internally whenever the size of the message is calculated.
     * Instead, use the `getMessageSize` function exported from the package.**
     */
    _size?: number;

    /**
     * The cost of the message content in tokens.
     *
     * **Do not use this property as it is only set internally whenever the cost of the message is calculated.
     * Instead, use the `getMessageCost` function exported from the package.**
     */
    _cost?: number;
};

export type AddMessageListener = (message: ConversationMessage) => void;

export type RemoveMessageListener = (message: ConversationMessage) => void;
