import { Alert, List, Anchor, Center, Button } from "@mantine/core";
import { FaExclamationTriangle } from "react-icons/fa";
import usePersistence from "../hooks/usePersistence";

// const f = new Function("a", "b", "return a - b");
// console.log(f(2, 1));

interface FunctionsWarningProps {
    children?: React.ReactNode;
}

const FunctionsWarning = ({ children }: FunctionsWarningProps) => {
    const { dismissFunctionsWarning, persistence } = usePersistence();

    if (!persistence.functionsWarning) return <>{children}</>;

    return (
        <Alert
            color="yellow"
            icon={<FaExclamationTriangle />}
            title="Functions Risks"
        >
            <List type="ordered" pr="md">
                <List.Item>
                    Functions usage costs are not currently calculated.
                </List.Item>
                <List.Item>
                    If you specify a function's code to run, it will executed
                    using a JavaScript{" "}
                    <Anchor href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function">
                        Function
                    </Anchor>{" "}
                    object, which is safer than "eval" but still has security
                    risks if you copy and paste code from the internet or your
                    device is compromised.
                </List.Item>
                <List.Item>
                    Function parameters generated by the assistant are not
                    validated before being passed to the function. You should
                    validate them yourself.
                </List.Item>
                <List.Item>
                    Overall, functions in this app are relatively limited in
                    terms of functionnality and are not intended to be used for
                    anything other than simple procedures.
                </List.Item>
            </List>
            <Center mt="xs">
                <Button onClick={dismissFunctionsWarning}>
                    I understand the risks. Unlock functions.
                </Button>
            </Center>
        </Alert>
    );
};

export default FunctionsWarning;
