name: Bug Report
description: File a bug report about the library or one of its implementations
title: "[Bug]: "
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!
        Before you submit, please make sure to check out the [contributing guidelines on bug reporting](https://github.com/maxijonson/gpt-turbo/blob/master/CONTRIBUTING.md#reporting-bugs) and make sure that you are using the latest version.
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Which part of GPT Turbo is affected?
      multiple: true
      options:
        - "Library (gpt-turbo)"
        - "CLI (gpt-turbo-cli)"
        - "Web (gpt-turbo-web)"
        - "Nest (gpt-turbo-nest)"
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: |
        Describe the bug. 
        - Please use code blocks (with \`\`\`) to format your code and error messages.
        - Screenshots, GIFs, and videos are super helpful!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the bug
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: possibleFix
    attributes:
      label: Possible fix
      description: If you have an idea of how to fix the bug, please share it here
  - type: dropdown
    id: participate
    attributes:
      label: Participation
      description: Are you willing to submit a PR to fix this bug?
      options:
        - "Yes"
        - "No"
