import { ChatCompletionRequestMessageRole } from "../request/message.types.js";
import { ChatCompletionResponseMessageLogprob } from "./logprob.types.js";
import { ChatCompletionResponseMessageToolCall } from "./tool-call.types.js";

/**
 * A chat completion message generated by the model.
 */
export interface ChatCompletionResponseMessage {
    /**
     * The contents of the message.
     */
    content: string;

    /**
     * The tool calls generated by the model, such as function calls.
     */
    tool_calls: ChatCompletionResponseMessageToolCall[];

    /**
     * The role of the author of this message.
     */
    role: ChatCompletionRequestMessageRole | (string & {});

    /**
     * Log probability information for the choice.
     */
    logprobs: ChatCompletionResponseMessageLogprob | null;
}
