export interface ChatCompletionResponseMessageFunctionToolCall {
    /**
     * _Only for Chat Completion Response Chunk_
     */
    index?: number;

    /**
     * The ID of the tool call.
     */
    id: string;

    /**
     * The type of the tool.
     */
    type: "function";

    /**
     * The function that the model called.
     */
    function: {
        /**
         * The name of the function to call.
         */
        name: string;

        /**
         * The arguments to call the function with, as generated by the model in JSON format.
         * Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema.
         * Validate the arguments in your code before calling your function.
         */
        arguments: string;
    };
}

export interface ChatCompletionResponseMessageOtherToolCall {
    /**
     * The ID of the tool call.
     */
    id: string;

    /**
     * The type of the tool.
     */
    type: string;

    [key: string]: any;
}

export type ChatCompletionResponseMessageToolCall =
    | ChatCompletionResponseMessageFunctionToolCall
    | ChatCompletionResponseMessageOtherToolCall;
